### ISSUE TITLE
Unable to mount data path

### ISSUE THREAD

**Issue by cagy520** [bitnami/bitnami-docker-pgpool#66]
i try it command:
docker run --detach --rm  **-v /root/pgdata:/bitnami/postgresql/data** -p 5432:5432 --name pg-0 \
  --network my-network \
  --env REPMGR_PARTNER_NODES=pg-0,pg-1 \
  --env REPMGR_NODE_NAME=pg-0 \
  --env REPMGR_NODE_NETWORK_NAME=pg-0 \
  --env REPMGR_PRIMARY_HOST=pg-0 \
  --env REPMGR_PASSWORD=repmgrpass \
  --env POSTGRESQL_POSTGRES_PASSWORD=adminpassword \
  --env POSTGRESQL_USERNAME=customuser \
  --env POSTGRESQL_PASSWORD=custompassword \
  --env POSTGRESQL_DATABASE=customdatabase \
  bitnami/postgresql-repmgr:latest

But I didn't succeed

**Comment by juan131** [comment]
Hi @cagy520 

It looks like your issue is not related to `bitnami/pgpool` but `bitnami/postgresql-repmgr` instead. Please open a new issue describing the same topic at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues

Please also take a look to the section below in the README.md that explains the actual mountpoint you need to use to persist your data:

- https://github.com/bitnami/bitnami-docker-postgresql-repmgr#persisting-your-application
